# -*- coding: utf-8 -*-
"""HW5_Bogdan_Tanasa_problem4_embeddings_glove.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJ9gYsBQISqkaoYYDgqEb1kU38F6BdNm
"""



import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance



glove_embedding = WordEmbeddings("glove")

Sentence1 = "I went to a bank to deposit money."
Sentence2 = "I sat near a bank of a river."

sentence_1 = Sentence(Sentence1)
sentence_2 = Sentence(Sentence2)

print(sentence_1)
print(sentence_2)

glove_embedding.embed(sentence_1)
print(sentence_1[4])
print(sentence_1[4].embedding)
sentence_1[4].embedding.shape

glove_embedding.embed(sentence_2)
print(sentence_2[4])
print(sentence_2[4].embedding)
sentence_2[4].embedding.shape



glove_dist = distance.euclidean( np.array(sentence_1[4].embedding),
                                 np.array(sentence_2[4].embedding ))

print(glove_dist)

